# -*- coding: utf-8 -*-
"""Task-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QahL09rPYd2xF9bzyiX4p_sD1uW58U-
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import numpy as np

df = pd.read_csv('/content/super_store_Data (1).csv', encoding='latin1')

df.head()

df.shape

df.dtypes

df.describe()

category_sales = df.groupby('Category')['Sales'].sum().reset_index()
top_category = category_sales.loc[category_sales['Sales'].idxmax()]
print(f"Highest revenue category: {top_category['Category']}")
print(f"sales amount ${top_category['Sales']}")

plt.figure(figsize=(12, 6))
sns.barplot(data=category_sales, x='Category', y='Sales', palette='viridis')
plt.title('Revenue by Product Category')
plt.xlabel('Category')
plt.ylabel('Sales($)')
plt.show()

